#goal definition
# Mapping Command Enumeration
uint8 STOP    = 0
uint8 MAP     = 1
uint8 ACTUATE = 3 # e.g. prune/pick/thin

uint8 command

cares_msgs/ScanningGoal[] scanning_goals
cares_msgs/MetricExtractionGoal metric_goal
---
#result definition
uint8 result
---
#feedback

#Enumeration
uint8 INIT       = 0
uint8 SCANNING   = 1
uint8 EXTRACTING = 2
uint8 ACTUATING  = 3
uint8 STOPPING   = 4
#Task status
uint8 status

cares_msgs/ScanningFeedback[] scanning_feedback
cares_msgs/MetricExtractionFeedback[] metric_feedback